[features]
seeds = false
skip-lint = false

[programs.devnet]
presale = "9oemjxjE2zFJFVRynHVmWg1nTMWgTM3hGCetuAJkG21U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# === DODAJ TĘ SEKCJĘ ===
[toolchain]
anchor_version = "0.30.1"