[package]
name = "presale"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "phoenix_presale"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
# --- POPRAWKA: Ujednolicono wersje i funkcje ---
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
anchor-spl = "0.30.1"

# === DODANIE WYMAGANEJ KONFIGURACJI ===
[profile.release]
overflow-checks = true